analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#D7CECF'
    - '#030102'
    - '#B4A3A3'
    - '#775D5B'
    - '#B46543'
  rhythmicContrast: 0
typography_spectrum: 0.5139635
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5193341
favicon: null
name: 'A&M'
